### ISSUE TITLE
.astro extension not being recognized / basic setup issue

### ISSUE THREAD

**Issue by tjex** [virchau13/tree-sitter-astro#11]
Hello. 

Unfortunately I've run out of ideas of how to get neovim to recognize `.astro` files. 
Currently I have:
- [x] installed `astro-language-server`
- [x] setup `astro-language-server` with `nvim-lsp`
- [x] installed the treesitter parsers `css` `typescript` `tsx` and also `astro` (just in case)
- [x] tried both options of adding `astro` in `ftdetect/`

All to no avail. 

Specs: neovim 0.8. MacOS

`nvim/ftdetect/astro.lua`:   

```lua
vim.filetype.add({
    extension = {
        astro = "astro"
    }
})
```

Here is what I see when in an `.astro` file via `LspInfo`: 

<img width="1093" alt="Screen Shot 2023-03-13 at 16 27 04" src="https://user-images.githubusercontent.com/83029642/224766365-56e1f286-c0cf-4f4d-978e-9e980394344e.png">

And also worth noting, that when I check `TSModuleInfo` that `astro` is not found for any of its options:     
<img width="529" alt="Screen Shot 2023-03-13 at 17 30 11" src="https://user-images.githubusercontent.com/83029642/224766569-2c460094-2011-4db9-88a3-585591a14d7d.png">

It is hover shown under `TSInstallInfo` as being installed.

 <img width="320" alt="Screen Shot 2023-03-13 at 17 35 33" src="https://user-images.githubusercontent.com/83029642/224766872-eb1b3110-e056-4795-b60e-b8bd2bb8d05f.png">

thanks for any and all help

**Comment by virchau13** [comment]
Your config doesn't look like it's being sourced; note highlight=true in your config vs highlight=false in TSConfigInfo.

**Comment by tjex** [comment]
So it seems that it was indeed an issue with my nvim config initialisation. 
The treesitter config was being sourced at the start of my init lua, but apparently it was being broken by something after it... 
Placed my treesitter setup call as the very last step in init.lua and it's working now.

**Comment by tjex** [comment]
Was actually because of this code at the start of my treesitter.lua config file:

```
local status_ok, treesitter = pcall(require, "treesitter" )
if not status_ok then
    return
end
```
That's what I get for coping pasting code which I only partially understand what it does / or at least, not understand well enough how it could cause a problem.
