### ISSUE TITLE
Syntax highlight is broken :(

### ISSUE THREAD

**Issue by Odas0R** [virchau13/tree-sitter-astro#13]
![image](https://user-images.githubusercontent.com/32167770/229900615-22083711-c955-48da-88c0-c66f772d56ed.png)

Using brackets `{}` breaks the syntax highlights.

Let me know what you need!

I'm using https://github.com/ellisonleao/gruvbox.nvim

**Comment by virchau13** [comment]
Have you taken a look at the troubleshooting section in the README? Sounds like you're missing a parser dependency.

**Comment by Odas0R** [comment]
Sorry for the late reply.

I had all parser dependencies from the time I wrote the issue!

I will try again later, right now I'm using another solution :+1:. Will give more feedback.

**Comment by Odas0R** [comment]
Still, have weird syntax highlights. (Changed my color scheme)

![image](https://user-images.githubusercontent.com/32167770/235516612-ec8a58a4-18ff-43be-9af5-3ea7b8d7e283.png)

I already had all the dependencies, but done again `TSIntall tsx css typescript`

**Comment by virchau13** [comment]
Yep, I can reproduce. Seems like the issue was the apostrophe in the comment: my raw-text scanner just straight up doesn't handle comments 🤦. I'm surprised this didn't come up earlier to be honest. Should be fixed soon.

**Comment by Odas0R** [comment]
Awesome, thanks a lot, great work! :)
