### ISSUE TITLE
Component Template Tags

### ISSUE THREAD

**Issue by davelongdev** [virchau13/tree-sitter-astro#17]
hi there.  It would be nice to have component template tags get highlighted with their own color like they do when using the astro vscode extension so they stand out as different from other html elements.  I don't have a ton of nvim/treesitter experience, but it seems like the best place to implement this would be in the grammar so they appear as unique in the syntax tree?  i'm not sure, though, what the best way to implement this highlighting is.  i'm trying to understand treesitter better, but i'm not really that deep into it yet.  any thoughts or guidance would be appreciated.  thanks.

**Comment by virchau13** [comment]
Sorry, I'm not sure what you mean. Are you referring to highlighting of custom components? (so builtin tags get different highlighting from non-builtin tags)

Can you send an example VSCode screenshot?

**Comment by davelongdev** [comment]
Hey.  Thanks for getting back to me.  So in the screen shot I'm attaching, I've imported two components in the frontmatter - MainLayout and PostCard.  In, VScode with the astro extension, the html tags for these two components are yellow in the , which is different from the other red html tags.  In nvim, though, all the html tags are the same color, at least in my setup.  Hope this makes sense.


<img width="876" alt="Screen Shot 2023-08-21 at 9 52 57 AM" src="https://github.com/virchau13/tree-sitter-astro/assets/122243388/233d9216-0f1d-4c02-96f2-d4ed980cf35a">

Also, take a look at the Component Template section of the Astro docs  (link below).

https://docs.astro.build/en/core-concepts/astro-components/

**Comment by devgioele** [comment]
The title of the issue does not explain the problem.

I confirm that the highlighting is not feature-complete. Builtin html tags should have another color than non-builtin tags.

**Comment by virchau13** [comment]
Sorry for the wait. Implemented in above PR.
