### ISSUE TITLE
Missing HTML highlights in nvim

### ISSUE THREAD

**Issue by lygamac** [virchau13/tree-sitter-astro#20]
Everything works but HTML highlights. Doesn't seem to happen to the Helix editor (which uses a fixed commit, perhaps some of the commit caused this?)

![image](https://github.com/virchau13/tree-sitter-astro/assets/49118209/c3260a7a-2c09-41a2-a5ac-f558424794ec)

```
Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - htmldjango          ✓ . ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓

```

**Comment by lygamac** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/3497

**Comment by virchau13** [comment]
Sorry for not responding earlier, I was a bit busy.

This issue isn't caused by that one, as the Astro parser does not use HTML injections, but rather copies the grammar rules directly.

**Comment by virchau13** [comment]
This works perfectly fine on my machine, so it appears to be a configuration issue on your end. What's the output of `:checkhealth`? Do highlights in `.html` files work properly?

**Comment by lygamac** [comment]
Found the problem: The color scheme.

Indeed, `.html` has "no highlight" as well, but changing even to a built-in theme allows the highlighting to appear. Guess the colorscheme I am using is outdated.
