### ISSUE TITLE
Error when using a self closing script tag

### ISSUE THREAD

**Issue by Akeboshiwind** [virchau13/tree-sitter-astro#27]
With the following document:
```astro
---
---
<script />
<div>this isn't highlighted</div>
```

I get the following in the playground:
```
frontmatter [0, 0] - [1, 3]
  frontmatter_js_block [0, 3] - [0, 3]
ERROR [2, 0] - [3, 33]
  tag_name [2, 1] - [2, 7]
  attribute_js_expr [2, 10] - [3, 13]
  attribute_js_expr [3, 14] - [3, 33]
```

And it looks like this:
<img width="341" alt="Screenshot 2024-04-23 at 11 42 00" src="https://github.com/virchau13/tree-sitter-astro/assets/8889986/f0b4b3c4-719a-4c68-90c1-15f8642f3e7c">

**Comment by Akeboshiwind** [comment]
Oddly seems to only happen with the script tag 🤔

**Comment by virchau13** [comment]
Oh, self-closing script tags aren't allowed in HTML5. (Are they allowed in Astro?)
