### ISSUE TITLE
Treesitter not working on the {typescript} part 

### ISSUE THREAD

**Issue by ubmit** [virchau13/tree-sitter-astro#4]
I've already installed the `astro` grammar by running `:TSInstall astro` and I've also ran `:TSUpdate`, however it seems that the {typescript} parser isn't working. I added the `astro.lua` file at `~/.config/nvim/ftdetect/astro.lua` as recommended as well. I'm using nvim v0.8.0.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/8797405/200098671-0b784cac-9bce-4238-8356-aa0d8402c5de.png">

Am I missing something? I've never had to install a grammar before.

Edit: for comparison, here is VS Code with the official Astro extension

<img width="469" alt="image" src="https://user-images.githubusercontent.com/8797405/200098758-8352914b-f8be-4d65-82cd-00b5ce3c0492.png">

**Comment by virchau13** [comment]
Sorry for the late response.

Have you taken a look at the troubleshooting section in the README? Sounds like you're missing a parser dependency.

**Comment by ubmit** [comment]
It seems that I was missing the `typescript` parser, thanks @virchau13 🙌
