### ISSUE TITLE
Add JavaScript expressions support

### ISSUE THREAD

**Issue by joshmedeski** [virchau13/tree-sitter-astro#6]
The [Astro component template](https://docs.astro.build/en/core-concepts/astro-components/#the-component-template) supports JSX-like syntax for JavaScript expressions.

```jsx
<!-- Mix HTML with JavaScript expressions, similar to JSX: -->
<ul>
  {myFavoritePokemon.map((data) => <li>{data.name}</li>)}
</ul>
```

<img width="1496" alt="Screenshot 2022-12-26 at 2 47 15 PM" src="https://user-images.githubusercontent.com/2036594/209582606-1cc8a78a-7cb5-4278-a926-9e438647816d.png">

As you can see, this isn't supported yet by this plugin. Can we add this feature? I'm new to treesitter development but I'm happy to help if I'm given some resources or direction on how to do this.

**Comment by virchau13** [comment]
Highlighting JSX does work:
![image](https://user-images.githubusercontent.com/16955157/209600906-eaeca661-9fc9-47ff-9d26-539b3aada00b.png)

Try https://github.com/virchau13/tree-sitter-astro#parser-dependencies

**Comment by joshmedeski** [comment]
Sweet, I didn't have `tsx` installed yet so `:TSInstall tsx` did the trick!
