### ISSUE TITLE
Support Sass, Less, and Stylus in `<style>` tags

### ISSUE THREAD

**Issue by tobias-edwards** [virchau13/tree-sitter-astro#9]
Astro style tags support Sass and SCSS out of the box via `<style lang="sass">` or `<style lang="scss">` (along with other CSS preprocessors): https://docs.astro.build/en/guides/styling/#sass-and-scss

Will you be able to add syntax highlighting for these preprocessors when used with the `lang` attribute, please?

**Comment by virchau13** [comment]
I don't think there exists a Tree-sitter grammar for Sass, but I can certainly do it for SCSS.

**Comment by tobias-edwards** [comment]
Awesome thank you for this! Works for me using the latest treesitter :)
